apiVersion: apps/v1
kind: Deployment

metadata:
  name: flask-app
  namespace: dev

spec:
  replicas: 2

  selector:
    matchLabels:
      app: flask

  template:
    metadata:
      labels:
        app: flask
      
    spec:
    
      serviceAccountName: flask-sa

      containers:
        - name: flask
          image: anadi07/flaskapp:latest
          imagePullPolicy: Always

          ports:
            - containerPort: 5000

          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "500m"

          env:
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: flask-config
                  key: DB_HOST

            - name: DB_PORT
              value: "5432"

            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: flask-config
                  key: DB_NAME

            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: DB_USER

            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: DB_PASSWORD

          readinessProbe:
            httpGet:
              path: /ready
              port: 5000
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 2
            failureThreshold: 3
            successThreshold: 1