{{- if .Values.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "flask-app.fullname" . }}
  namespace: {{ .Values.serviceMonitor.namespace }}
  labels: {release: monitoring}
spec:
  selector:
    matchLabels: {app.kubernetes.io/name: {{ include "flask-app.name" . }}}
  namespaceSelector:
    matchNames: [{{ .Release.Namespace }}]
  endpoints:
    - {port: http, path: /metrics, interval: {{ .Values.serviceMonitor.interval }}}
{{- end }}
