apiVersion: v1
kind: Service
metadata:
  name: {{ include "flask-app.fullname" . }}
  labels: {app.kubernetes.io/name: {{ include "flask-app.name" . }}
spec:
  selector: {app.kubernetes.io/name: {{ include "flask-app.name" . }}}
  ports: [{name: http, port: {{ .Values.service.port }}, targetPort: http}]
  type: {{ .Values.service.type }}
