name: Flask CI/CD

on:
  push:
    branches:
      - main

jobs:
  test-and-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Check Python syntax
        run: python -m py_compile app.py

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker image
        run: docker build -t anadi07/flaskapp:${{ github.sha }} .

      - name: Push Docker image
        run: docker push anadi07/flaskapp:${{ github.sha }}

  deploy:
    needs: test-and-build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create Kind cluster
        uses: helm/kind-action@v1.12.0

      - name: Check Kubernetes cluster
        run: kubectl get nodes

      - name: Create Kubernetes Secret
        run: kubectl apply -f secret.yaml

      - name: Create ConfigMap
        run: kubectl apply -f configmap.yaml

      - name: Deploy PostgreSQL
        run: kubectl apply -f postgres-deployment.yaml

      - name: Deploy PostgreSQL Service
        run: kubectl apply -f postgres-service.yaml

      - name: Wait for PostgreSQL
        run: kubectl rollout status deployment/postgres --timeout=120s

      - name: Deploy Flask
        run: kubectl apply -f deployment.yaml

      - name: Update Flask image
        run: kubectl set image deployment/flask-app flask=anadi07/flaskapp:${{ github.sha }}

      - name: Deploy Flask Service
        run: kubectl apply -f service.yaml

      - name: Wait for Flask rollout
        run: kubectl rollout status deployment/flask-app --timeout=120s

      - name: Show Kubernetes resources
        run: kubectl get pods,svc,deployments

      - name: Verify Flask pods
        run: kubectl get pods -l app=flask